name="BACKTRADER OPTIONS TESTING"

standard_fee=0.50
incur_fees=false
data_loader_type = 'SQL_DATA_LOADER'
data_format_settings = "sql_server_cboe_settings.toml"
database = "spx_options_data"
signals_database = "signals_db"
slippage=0.05
apply_slippage_entry=false
apply_slippage_exit=false

