[SELECT_OPTIONS_QUERY]
select = 'select '
from = ' from options o inner join symbols s on o.symbol_id = s.id inner join option_values ov on o.id = ov.option_id'
where = " where symbol ='{symbol}' and quote_date between CONVERT(datetime2, '{start_date}') and CONVERT(datetime2, '{end_date}') "
order_by = ' order by quote_date, expiration, strike'
datetime_list_query = "select distinct quote_date, quote_date as col from stock_prices where quote_date between CONVERT(datetime2, '{start_date}') and CONVERT(datetime2, '{end_date}') order by quote_date"
quote_datetime_field = "quote_date"

[FIELD_MAPPING]
option_id = 'o.id as option_id'
symbol = 'symbol'
strike = 'strike'
expiration = 'expiration'
option_type = 'option_type'
quote_datetime = 'quote_date as quote_datetime'
spot_price = 'underlying_price as spot_price'
bid = 'bid'
ask = 'ask'
price = 'price'
delta = 'delta'
gamma = 'gamma'
theta = 'theta'
vega = 'vega'
open_interest = 'open_interest'
implied_volatility = 'implied_volatility'